### ISSUE TITLE
Black Triangles Appearing

### ISSUE THREAD

**Issue by Madeck** [robertcupisz/LightShafts#5]
Very nice package that really helps creating interesting atmospheres. It seems however that there are strange black triangles that appear for some reason I cannot fully explain. In the following screenshot they are not all produced by the same light source.

![Black Triangle Bug Screenshot](http://f.cl.ly/items/0M1n1A1j0C1b0t2g2i08/Image%202014-12-13%20at%204.42.56%20PM.png)

It it maybe clearer when animated:

![Black Triangle Bug Animation](http://cld.mdck.ca/YxnW/Screen%20Recording%202014-12-13%20at%2004.47%20PM.gif)

Any idea of what could be causing this?

EDIT: It seems to happen only at the edge of the light projection frustum. Here’s a more useful GIF:

![Black Bar Bug Animation 2](http://cld.mdck.ca/YxFf/Screen%20Recording%202014-12-14%20at%2001.29%20PM.gif)

**Comment by rmattson** [comment]
I'm seeing this in a project I'm working on when I'm using my laptop, which is a MacBook Pro (mid-2014), Core i5, Intel Iris 5100 graphics processor with 1.5GB shared memory, on Yosemite (10.10.3). (This doesn't happen for a colleague who has a MacBook Pro with an NVIDIA graphics chip in it. And perhaps the graphics hardware is a red herring anyway.)

I am trying to create a separate project that reproduces the problem, but somewhat frustratingly it doesn't repro in a new project, only in the main project I've got the LightShafts working in. I can't dive into the investigating the differences just yet, but next chance I get I will see if I can sort out a repro case.

**Comment by myshkinent** [comment]
Hi,
Thanks for making this, I really like the look of the effect. I was experiencing the same issue as Madeck and couldn't find a solution anywhere, but I think I managed to reproduce the problem.

After switching back and forth between 2 cameras, one that had the black bars and one that didn't, it looks like (for me at least) the error happens when "HDR" is enabled on the camera. I could also avoid the black bars by increasing the light shaft depth threshold to 20 or more, but this results in poor quality edges.

If you have a workaround for this that would be brilliant - if not, it looks like the best option is to not use HDR at the same time as light shafts.

**Comment by robertcupisz** [comment]
I think it's some volatile precision issue, which results in a NaN in some specific cases, but I haven't been able to reproduce it myself yet. Would be great if you managed to create a small scene reproducing this.

**Comment by myshkinent** [comment]
Hey,
I managed to reproduce it with a scene just containing a spotlight with shafts and the Unity standard FPSController prefab (with HDR enabled). Here's the scene file - not sure if you'd need the whole project to test it?

https://www.dropbox.com/s/7qve771t97wpm36/ShaftTest.unity?dl=0

**Comment by robertcupisz** [comment]
Hey, thanks! Haven't tried opening it yet, but best would be with the rest of the project, since the scene file only contains references to any assets you've used. Also please let me know which Unity version are you seeing the issue in. Cheers.

**Comment by myshkinent** [comment]
OK, this is weird - I made a new project to demonstrate this effect, but the light shaft won't work at all giving the error "Render texture support (including RFloat and RGFloat) and shader model 3.0 required."
It works fine in my main project so I'm not sure what the new blank project might be missing, but now I can't get the test to work at all... possibly some graphical setting or dependant asset? Both OS and Unity version are the same.

**Comment by robertcupisz** [comment]
What graphics API is the new project using? On windows, it's the last thing in the title bar of the window, e.g. <DX11>.

**Comment by myshkinent** [comment]
Would that be OpenGL 3.2? It's the same on both my main project and the test scene.
I should add that since unchecking HDR from my main camera, I've been using the light shafts without a problem now.

The only other weird thing that happened was a light getting culled when moving past it - but when I deleted it and added a new light in, the new one didn't get culled. So I have no idea what happened there!
